export const college_options = [
  'University of Puerto Rico, Arecibo',
  'University of Puerto Rico, Aguadilla',
  'University of Puerto Rico, Bayamon',
  'University of Puerto Rico, Carolina',
  'University of Puerto Rico, Cayey',
  'University of Puerto Rico, Ciencias Medicas',
  'University of Puerto Rico, Humacao',
  'University of Puerto Rico, Mayaguez',
  'University of Puerto Rico, Rio Piedras',
  'University of Puerto Rico, Ponce',
  'University of Puerto Rico, Utuado'
];

export const major_options = [
  'ICOM',
  'INEL',
  'INQU',
  'INCI',
  'INME',
  'ININ',
  'OTHER'
];

export const hometown_options = [
  'Adjuntas',
  'Aguada',
  'Aguadilla',
  'Aguas Buenas',
  'Aibonito',
  'Añasco',
  'Arecibo',
  'Arroyo',
  'Barceloneta',
  'Barranquitas',
  'Bayamón',
  'Cabo Rojo',
  'Caguas',
  'Camuy',
  'Carolina',
  'Cataño',
  'Cayey',
  'Ceiba',
  'Ciales',
  'Cidra',
  'Coamo',
  'Comerío',
  'Corozal',
  'Culebra',
  'Dorado',
  'Fajardo',
  'Florida',
  'Guánica',
  'Guayama',
  'Guayanilla',
  'Guaynabo',
  'Gurabo',
  'Hatillo',
  'Hormigueros',
  'Humacao',
  'Isabela',
  'Jayuya',
  'Juana Díaz',
  'Juncos',
  'Lajas',
  'Lares',
  'Las Marías',
  'Las Piedras',
  'Loiza',
  'Luquillo',
  'Manatí',
  'Maricao',
  'Maunabo',
  'Mayagüez',
  'Moca',
  'Morovis',
  'Naguabo',
  'Naranjito',
  'Orocovis',
  'Patillas',
  'Peñuelas',
  'Ponce',
  'Quebradillas',
  'Rincón',
  'Rio Grande',
  'Sabana Grande',
  'Salinas',
  'San Germán',
  'San Juan',
  'San Lorenzo',
  'San Sebastián',
  'Santa Isabel',
  'Toa Alta',
  'Toa Baja',
  'Trujillo Alto',
  'Utuado',
  'Vega Alta',
  'Vega Baja',
  'Vieques',
  'Villalba',
  'Yabucoa',
  'Yauco'
];
